### ISSUE TITLE
Rained doesn't start

### ISSUE THREAD

**Issue by Alfor564** [pkhead/rained#11]
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
Repeat 2 times:
--------------------------------
   at Bgfx_cs.Bgfx.init(Init*)
--------------------------------
   at Glib.RenderContext..ctor(Glib.Window, Boolean, Glib.RendererType)
   at Glib.RenderContext.Init(Glib.Window, Boolean, Glib.RendererType)
   at RainEd.Boot+<>c__DisplayClass23_0.<LaunchEditor>b__1()
   at Glib.Window.OnLoad()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Glib.Window.Initialize()
   at RainEd.Boot.LaunchEditor()
   at RainEd.Boot.Main(System.String[])

**Comment by pkhead** [comment]
I'm aware of this bug and working on a fix for it. Sorry for the inconvenience. Trying running v2.0.3, or resort to b1.5.3 if that doesn't work.

**Comment by pkhead** [comment]
Test the newest nightly build. I've tested it with someone else who had the same issue and it worked for them... but I do want to make sure it works for you before closing the issue.

**Comment by pkhead** [comment]
I've uploaded the fix to v2.1.1 so you may test that as well.
