### ISSUE TITLE
Rained doesn't start 2

### ISSUE THREAD

**Issue by Alfor564** [pkhead/rained#13]
If anything, version rained 2.1.3.
Unhandled exception. System.PlatformNotSupportedException: GLFW is not supported on this platform.
   at Silk.NET.Windowing.Glfw.GlfwPlatform.ThrowUnsupported()
   at Silk.NET.Windowing.Glfw.GlfwPlatform.CreateWindow(WindowOptions options)
   at Silk.NET.Windowing.Window.Create(WindowOptions options)
   at Glib.WindowOptions.CreateSilkWindow() in C:\Users\nabca\Documents\src\cs\rained\src\Glib\WindowOptions.cs:line 129
   at Glib.Window..ctor(WindowOptions options) in C:\Users\nabca\Documents\src\cs\rained\src\Glib\Window.cs:line 229
   at RainEd.Boot.LaunchEditor() in C:\Users\nabca\Documents\src\cs\rained\src\Rained\Boot.cs:line 141
   at RainEd.Boot.Main(String[] args) in C:\Users\nabca\Documents\src\cs\rained\src\Rained\Boot.cs:line 53

**Comment by pkhead** [comment]
Are you on Windows?

**Comment by Alfor564** [comment]
Yeah, sure. And another question, can this error be because I have hardware acceleration turned off?

**Comment by pkhead** [comment]
Probably. Rained doesn't have a software renderer, so it can't display anything without hardware acceleration. I'd assume it'd just throw an error -- maybe this is the error you would get.

**Comment by pkhead** [comment]
Actually, how did you "turn off hardware acceleration"? I suspect turning it off means that the Windows desktop doesn't use your graphics cards, but I think Rained would still be able to. In that case, I have no idea why this error is occuring, as based on the stack trace it occurs when creating the window. I suppose make sure that the file `glfw3.dll` exists alongside `Rained.exe`?
